### PR TITLE
Issue 354 default values for min/max zoom in layers config

### LINKED ISSUE #360: Debug page is fetching wrong zoom
If I open a new window, turn on developer tools, and go to `http://localhost:8080/#10.35/49.243/-122.929` I find the debug page fetching the tile `http://localhost:8080/maps/bolder/5/5/10.pbf`

This is not the right zoom, and leads to obvious problems.

The JSON files fetched by the page are attached

`/capabilities`
```json
{
    "maps": [
        {
            "attribution": "",
            "bounds": [
                -180,
                -85.0511,
                180,
                85.0511
            ],
            "capabilities": "http://localhost:8080/capabilities/bolder.json",
            "center": [
                0,
                0,
                0
            ],
            "layers": [
                {
                    "maxzoom": 9,
                    "minzoom": 0,
                    "name": "water",
                    "tiles": [
                        "http://localhost:8080/maps/bolder/water/{z}/{x}/{y}.pbf"
                    ]
                },
                {
                    "maxzoom": 0,
                    "minzoom": 10,
                    "name": "water_names",
                    "tiles": [
                        "http://localhost:8080/maps/bolder/water_names/{z}/{x}/{y}.pbf"
                    ]
                },
                {
                    "maxzoom": 0,
                    "minzoom": 8,
                    "name": "forests",
                    "tiles": [
                        "http://localhost:8080/maps/bolder/forests/{z}/{x}/{y}.pbf"
                    ]
                },
                {
                    "maxzoom": 9,
                    "minzoom": 5,
                    "name": "transport",
                    "tiles": [
                        "http://localhost:8080/maps/bolder/transport/{z}/{x}/{y}.pbf"
                    ]
                }
            ],
            "name": "bolder",
            "tiles": [
                "http://localhost:8080/maps/bolder/{z}/{x}/{y}.pbf"
            ]
        }
    ],
    "version": "version not set"
}
```

`/style.json`
```
{
    "center": [
        0,
        0
    ],
    "layers": [
        {
            "id": "water",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "fill-color": "rgba(23,197,186,0.1)",
                "fill-outline-color": "#17c5ba"
            },
            "source": "bolder",
            "source-layer": "water",
            "type": "fill"
        },
        {
            "id": "water_names",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "circle-color": "#2092da",
                "circle-radius": 3
            },
            "source": "bolder",
            "source-layer": "water_names",
            "type": "circle"
        },
        {
            "id": "forests",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "fill-color": "rgba(246,167,155,0.1)",
                "fill-outline-color": "#f6a79b"
            },
            "source": "bolder",
            "source-layer": "forests",
            "type": "fill"
        },
        {
            "id": "transport",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "line-color": "#29f7c2"
            },
            "source": "bolder",
            "source-layer": "transport",
            "type": "line"
        }
    ],
    "name": "bolder",
    "sources": {
        "bolder": {
            "type": "vector",
            "url": "http://localhost:8080/capabilities/bolder.json"
        }
    },
    "version": 8
}
```

`/bolder.json`
```json
{
    "attribution": "",
    "bounds": [
        -180,
        -85.0511,
        180,
        85.0511
    ],
    "center": [
        0,
        0,
        0
    ],
    "data": [],
    "description": null,
    "format": "pbf",
    "grids": [],
    "legend": null,
    "maxzoom": 5,
    "minzoom": 0,
    "name": "bolder",
    "scheme": "xyz",
    "template": null,
    "tilejson": "2.1.0",
    "tiles": [
        "http://localhost:8080/maps/bolder/{z}/{x}/{y}.pbf"
    ],
    "vector_layers": [
        {
            "extent": 4096,
            "geometry_type": "polygon",
            "id": "water",
            "maxzoom": 9,
            "minzoom": 0,
            "name": "water",
            "tiles": [
                "http://localhost:8080/maps/bolder/water/{z}/{x}/{y}.pbf"
            ],
            "version": 2
        },
        {
            "extent": 4096,
            "geometry_type": "point",
            "id": "water_names",
            "maxzoom": 0,
            "minzoom": 10,
            "name": "water_names",
            "tiles": [
                "http://localhost:8080/maps/bolder/water_names/{z}/{x}/{y}.pbf"
            ],
            "version": 2
        },
        {
            "extent": 4096,
            "geometry_type": "polygon",
            "id": "forests",
            "maxzoom": 0,
            "minzoom": 8,
            "name": "forests",
            "tiles": [
                "http://localhost:8080/maps/bolder/forests/{z}/{x}/{y}.pbf"
            ],
            "version": 2
        },
        {
            "extent": 4096,
            "geometry_type": "line",
            "id": "transport",
            "maxzoom": 9,
            "minzoom": 5,
            "name": "transport",
            "tiles": [
                "http://localhost:8080/maps/bolder/transport/{z}/{x}/{y}.pbf"
            ],
            "version": 2
        }
    ],
    "version": "1.0.0"
}
```

JSON files have been pretty-printed for legibility.

### PR DESCRIPTION
**Pull request by ear7h**
This may also close #360 

Include some changes to the map.go file and it's internals for compatibility with pointers to their underlying values.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -90,10 +91,21 @@ func (c *Config) Validate() error {
...
 			}
 
+			// MaxZoom default
+			if l.MaxZoom == nil {
+				ph := uint(tegola.MaxZ)
+				l.MaxZoom = &ph
+			}
+			// MinZoom default
+			if l.MinZoom == nil {
+				ph := uint(tegola.MaxZ)
```
Comment (ARolek) [inline config/config.go]: this should be 0 for the MinZoom

**Comment by gdey** [comment]
fixes #354
